// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admins.sql

package database

import (
	"context"
)

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins (id, email, password_hash, recovery_hash)
VALUES (?, ?, ?, ?)
RETURNING id, email, password_hash, created_at, updated_at, recovery_hash
`

type CreateAdminParams struct {
	ID           string
	Email        string
	PasswordHash string
	RecoveryHash string
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRowContext(ctx, createAdmin,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.RecoveryHash,
	)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecoveryHash,
	)
	return i, err
}

const getAdmin = `-- name: GetAdmin :one
SELECT id, email, password_hash, created_at, updated_at, recovery_hash FROM admins LIMIT 1
`

func (q *Queries) GetAdmin(ctx context.Context) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdmin)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecoveryHash,
	)
	return i, err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, email, password_hash, created_at, updated_at, recovery_hash FROM admins WHERE email = ?
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdminByEmail, email)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecoveryHash,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, email, password_hash, created_at, updated_at, recovery_hash FROM admins WHERE ID = ?
`

func (q *Queries) GetAdminByID(ctx context.Context, id string) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdminByID, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecoveryHash,
	)
	return i, err
}

const resetAdmins = `-- name: ResetAdmins :exec
DELETE FROM admins
`

func (q *Queries) ResetAdmins(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetAdmins)
	return err
}

const updateAdminEmail = `-- name: UpdateAdminEmail :exec
UPDATE admins
SET email = ? , updated_at = datetime('now')
WHERE id = ?
`

type UpdateAdminEmailParams struct {
	Email string
	ID    string
}

func (q *Queries) UpdateAdminEmail(ctx context.Context, arg UpdateAdminEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminEmail, arg.Email, arg.ID)
	return err
}

const updateAdminPassword = `-- name: UpdateAdminPassword :exec
UPDATE admins 
SET password_hash = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateAdminPasswordParams struct {
	PasswordHash string
	ID           string
}

func (q *Queries) UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateAdminRecoveryHash = `-- name: UpdateAdminRecoveryHash :exec
UPDATE admins
SET recovery_hash = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateAdminRecoveryHashParams struct {
	RecoveryHash string
	ID           string
}

func (q *Queries) UpdateAdminRecoveryHash(ctx context.Context, arg UpdateAdminRecoveryHashParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminRecoveryHash, arg.RecoveryHash, arg.ID)
	return err
}
