// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admins.sql

package database

import (
	"context"
)

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins (id, email, password_hash)
VALUES (?, ?, ?)
RETURNING id, email, password_hash, created_at, updated_at
`

type CreateAdminParams struct {
	ID           string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRowContext(ctx, createAdmin, arg.ID, arg.Email, arg.PasswordHash)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, email, password_hash, created_at, updated_at FROM admins WHERE email = ?
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdminByEmail, email)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, email, password_hash, created_at, updated_at FROM admins WHERE ID = ?
`

func (q *Queries) GetAdminByID(ctx context.Context, id string) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdminByID, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAdminEmail = `-- name: UpdateAdminEmail :exec
UPDATE admins
SET email = ? , updated_at = datetime('now')
WHERE id = ?
`

type UpdateAdminEmailParams struct {
	Email string
	ID    string
}

func (q *Queries) UpdateAdminEmail(ctx context.Context, arg UpdateAdminEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminEmail, arg.Email, arg.ID)
	return err
}

const updateAdminPassword = `-- name: UpdateAdminPassword :exec
UPDATE admins 
SET password_hash = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateAdminPasswordParams struct {
	PasswordHash string
	ID           string
}

func (q *Queries) UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminPassword, arg.PasswordHash, arg.ID)
	return err
}
