// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: images.sql

package database

import (
	"context"
)

const countImagesByProductID = `-- name: CountImagesByProductID :one
SELECT COUNT(*) FROM product_images
WHERE product_id = ?
`

func (q *Queries) CountImagesByProductID(ctx context.Context, productID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countImagesByProductID, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProductImage = `-- name: CreateProductImage :one
INSERT INTO product_images (product_id, s3_key, cover)
VALUES (?, ? , ?)
RETURNING id, product_id, s3_key, cover, created_at
`

type CreateProductImageParams struct {
	ProductID int64
	S3Key     string
	Cover     int64
}

func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRowContext(ctx, createProductImage, arg.ProductID, arg.S3Key, arg.Cover)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.S3Key,
		&i.Cover,
		&i.CreatedAt,
	)
	return i, err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM product_images WHERE id = ?
`

func (q *Queries) DeleteImage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteImage, id)
	return err
}

const getImageByID = `-- name: GetImageByID :one
SELECT id, product_id, s3_key, cover, created_at FROM product_images WHERE id = ?
`

func (q *Queries) GetImageByID(ctx context.Context, id int64) (ProductImage, error) {
	row := q.db.QueryRowContext(ctx, getImageByID, id)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.S3Key,
		&i.Cover,
		&i.CreatedAt,
	)
	return i, err
}

const getImaginesByProductID = `-- name: GetImaginesByProductID :many
SELECT id, product_id, s3_key, cover, created_at FROM product_images 
WHERE product_id = ?
ORDER BY created_at ASC
`

func (q *Queries) GetImaginesByProductID(ctx context.Context, productID int64) ([]ProductImage, error) {
	rows, err := q.db.QueryContext(ctx, getImaginesByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductImage
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.S3Key,
			&i.Cover,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
