// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Admin struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    string
	UpdatedAt    string
	RecoveryHash string
}

type Product struct {
	ID          int64
	Name        string
	Slug        string
	Type        string
	Price       float64
	Quantity    int64
	Description sql.NullString
	IsAvailable int64
	VideoUrl    sql.NullString
	CreatedAt   string
	UpdatedAt   string
	About       sql.NullString
}

type ProductImage struct {
	ID        int64
	ProductID int64
	S3Key     string
	Cover     int64
	CreatedAt string
}
