// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package database

import (
	"context"
	"database/sql"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, slug, type, price, quantity, description, about, video_url)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, slug, type, price, quantity, description, is_available, video_url, created_at, updated_at, about
`

type CreateProductParams struct {
	Name        string
	Slug        string
	Type        string
	Price       float64
	Quantity    int64
	Description sql.NullString
	About       sql.NullString
	VideoUrl    sql.NullString
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Name,
		arg.Slug,
		arg.Type,
		arg.Price,
		arg.Quantity,
		arg.Description,
		arg.About,
		arg.VideoUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.Price,
		&i.Quantity,
		&i.Description,
		&i.IsAvailable,
		&i.VideoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.About,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = ?
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const filterProductByPrice = `-- name: FilterProductByPrice :many
SELECT id, name, slug, type, price, quantity, description, is_available, video_url, created_at, updated_at, about FROM products
WHERE is_available = 1
AND price >= ?
AND price <= ?
ORDER BY created_at DESC
LIMIT ?
`

type FilterProductByPriceParams struct {
	Price   float64
	Price_2 float64
	Limit   int64
}

func (q *Queries) FilterProductByPrice(ctx context.Context, arg FilterProductByPriceParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, filterProductByPrice, arg.Price, arg.Price_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Type,
			&i.Price,
			&i.Quantity,
			&i.Description,
			&i.IsAvailable,
			&i.VideoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.About,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT id, name, slug, type, price, quantity, description, is_available, video_url, created_at, updated_at, about FROM products
WHERE is_available = 1
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) GetAllProducts(ctx context.Context, limit int64) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getAllProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Type,
			&i.Price,
			&i.Quantity,
			&i.Description,
			&i.IsAvailable,
			&i.VideoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.About,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProductsAdmin = `-- name: GetAllProductsAdmin :many
SELECT id, name, slug, type, price, quantity, description, is_available, video_url, created_at, updated_at, about FROM products
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) GetAllProductsAdmin(ctx context.Context, limit int64) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getAllProductsAdmin, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Type,
			&i.Price,
			&i.Quantity,
			&i.Description,
			&i.IsAvailable,
			&i.VideoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.About,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, slug, type, price, quantity, description, is_available, video_url, created_at, updated_at, about FROM products
WHERE id = ?
`

func (q *Queries) GetProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.Price,
		&i.Quantity,
		&i.Description,
		&i.IsAvailable,
		&i.VideoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.About,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, name, slug, type, price, quantity, description, is_available, video_url, created_at, updated_at, about FROM products
WHERE slug = ? AND is_available = 1
`

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductBySlug, slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.Price,
		&i.Quantity,
		&i.Description,
		&i.IsAvailable,
		&i.VideoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.About,
	)
	return i, err
}

const searchProduct = `-- name: SearchProduct :many
SELECT id, name, slug, type, price, quantity, description, is_available, video_url, created_at, updated_at, about FROM products
WHERE is_available = 1
AND (
    name LIKE '%'|| ? || '%'
    OR description LIKE '%' || ? || '%'
    OR type LIKE '%' || ? || '%'
    OR slug LIKE '%' || ? || '%'
)
ORDER BY created_at DESC
LIMIT ?
`

type SearchProductParams struct {
	Column1 sql.NullString
	Column2 sql.NullString
	Column3 sql.NullString
	Column4 sql.NullString
	Limit   int64
}

func (q *Queries) SearchProduct(ctx context.Context, arg SearchProductParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, searchProduct,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Type,
			&i.Price,
			&i.Quantity,
			&i.Description,
			&i.IsAvailable,
			&i.VideoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.About,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = ?,
    slug = ?,
    type = ?,
    price = ?,
    quantity = ?,
    description = ?,
    about = ?,
    video_url = ?,
    is_available = ?,
    updated_at = datetime('now')
WHERE id = ?
RETURNING id, name, slug, type, price, quantity, description, is_available, video_url, created_at, updated_at, about
`

type UpdateProductParams struct {
	Name        string
	Slug        string
	Type        string
	Price       float64
	Quantity    int64
	Description sql.NullString
	About       sql.NullString
	VideoUrl    sql.NullString
	IsAvailable int64
	ID          int64
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.Name,
		arg.Slug,
		arg.Type,
		arg.Price,
		arg.Quantity,
		arg.Description,
		arg.About,
		arg.VideoUrl,
		arg.IsAvailable,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.Price,
		&i.Quantity,
		&i.Description,
		&i.IsAvailable,
		&i.VideoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.About,
	)
	return i, err
}

const updateProductVideoURL = `-- name: UpdateProductVideoURL :exec
UPDATE products
SET video_url = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateProductVideoURLParams struct {
	VideoUrl sql.NullString
	ID       int64
}

func (q *Queries) UpdateProductVideoURL(ctx context.Context, arg UpdateProductVideoURLParams) error {
	_, err := q.db.ExecContext(ctx, updateProductVideoURL, arg.VideoUrl, arg.ID)
	return err
}
